spring.application.name=ContactManager

# server conf.
server.port=7070

# datasource/database conf.
spring.datasouce.url = jdbc:mysql:///contact_db
spring.datasource.username=root
spring.datasource.password==root
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

# hibernate conf.
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.show-sql=true